# Generated by Django 5.0.7 on 2024-07-24 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace', models.PositiveSmallIntegerField(choices=[(1, 'Junior'), (2, 'Middle'), (3, 'Senior')], default=1, help_text='Position in the company?')),
            ],
        ),
    ]
